### ISSUE TITLE
[Review] Week 2 Project

### ISSUE THREAD

**Issue by FacerAin** [MINDYEOI/2021-Winter-WebStudy#2]
실제 주점에서 사용해도 될 정도로 디자인이랑 구성 정말 잘하셨습니다! 
2주차 과제 수고하셨습니다 :)

**Comment by FacerAin** [comment]
이미지, css 폴더를 만들어 관리해도 좋을 것 같습니다
아래 글 하단을 참고해주세요~!
http://blog.naver.com/PostView.nhn?blogId=anedthh&logNo=221276340326&categoryNo=66&parentCategoryNo=0

**Comment by mlnjeongpark** [comment]
감사합니다! 한가지 질문이 있습니다..!
![image](https://user-images.githubusercontent.com/71140885/107850913-5dc82d80-6e49-11eb-8edc-bf54740e8d2e.png)
폴더를 다음과 같이 나눴는데요!
main.html만 꺼내두고 나머지 html은 다 파일로 옮겼습니다..!
![image](https://user-images.githubusercontent.com/71140885/107851001-ddee9300-6e49-11eb-95a2-eb2f28a1b637.png)
html 폴더엔 이렇게 들어가있습니다!
근데 soju.html에서
![image](https://user-images.githubusercontent.com/71140885/107851011-f363bd00-6e49-11eb-97fc-eef11f28a79a.png)
하단에 블록해놓은 부분과 같이 thank.html로의 링크를
./thanks.html로 하면 오류가 나고,
![image](https://user-images.githubusercontent.com/71140885/107851035-1a21f380-6e4a-11eb-8835-7309e85a5a28.png)
이렇게 해야 오류가 나지 않습니다ㅠㅠ
제가 알기론 ./ 이 현재 웹페이지가 소속된 폴더이고
../가 현재 웹페이지의 부모폴더라고 알고있는데
./라고 해도 문제가 없어야하는 것이 아닌지요..?!ㅠㅠ
번거롭게 해드려 죄송합니다ㅠㅠ 늘 잘 가르쳐주셔서 정말 감사합니다!!

**Comment by FacerAin** [comment]
안녕하세요.\~
'./thanks.html'과 'thanks.html' 같은 의미라 동작 상의 차이는 없을 거에요~
실제로 저도 html 폴더를 만들어 위 예시를 테스트 해보았는데 문제가 없었어요!
아래 사항들을 한번 체크해보시면 좋을 것 같아요!
1. 파일이 새로 고침되지 않음 (코드 변경사항 적용 X)
2. 코드 오타 또는 파일/폴더 구성 누락

혹시 위 방법으로도 안된다면 오류 사진 첨부하여 다시 질문 부탁드려요~!
감사합니다 :)

**Comment by mlnjeongpark** [comment]
안녕하세요!!
다시 해보니 정말 되네요! 감사합니다!!
